// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoi4S0t_YD9wnABEeJzlb4EvFzN8MNARQ',
    appId: '1:192156437386:web:09fadb327e3671057f1673',
    messagingSenderId: '192156437386',
    projectId: 'video-surveillance-syste-91807',
    authDomain: 'video-surveillance-syste-91807.firebaseapp.com',
    storageBucket: 'video-surveillance-syste-91807.appspot.com',
    measurementId: 'G-XWQ68T0JNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-8-DNPlwUDMil12R1TFBTiCHh0eq9ZcA',
    appId: '1:192156437386:android:52427d771fb5e9717f1673',
    messagingSenderId: '192156437386',
    projectId: 'video-surveillance-syste-91807',
    storageBucket: 'video-surveillance-syste-91807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArRQ4uHGeqO0mN4HQ0ZFwxgJJmcgVUurc',
    appId: '1:192156437386:ios:65dbc692182cdfaf7f1673',
    messagingSenderId: '192156437386',
    projectId: 'video-surveillance-syste-91807',
    storageBucket: 'video-surveillance-syste-91807.appspot.com',
    iosBundleId: 'com.example.videoSurveillanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArRQ4uHGeqO0mN4HQ0ZFwxgJJmcgVUurc',
    appId: '1:192156437386:ios:a08af909d2d0dbbd7f1673',
    messagingSenderId: '192156437386',
    projectId: 'video-surveillance-syste-91807',
    storageBucket: 'video-surveillance-syste-91807.appspot.com',
    iosBundleId: 'com.example.videoSurveillanceSystem.RunnerTests',
  );
}
